--DROPS--
SET AUTOCOMMIT on; 
SET SERVEROUTPUT on;
 
-- Drops entidades
DROP TABLE VEHICULO CASCADE CONSTRAINTS; 
DROP TABLE VEHICULO_REFRIGERADO CASCADE CONSTRAINTS; 
DROP TABLE VEHICULO_ADR CASCADE CONSTRAINTS; 
DROP TABLE GPS CASCADE CONSTRAINTS; 
DROP TABLE PARADA CASCADE CONSTRAINTS; 
DROP TABLE RUTA CASCADE CONSTRAINTS; 
DROP TABLE ENVIO CASCADE CONSTRAINTS; 
DROP TABLE PAQUETE CASCADE CONSTRAINTS; 
DROP TABLE CLIENTE CASCADE CONSTRAINTS; 
DROP TABLE PERSONA CASCADE CONSTRAINTS; 
DROP TABLE EMPRESA CASCADE CONSTRAINTS; 
DROP TABLE EMPLEADO CASCADE CONSTRAINTS; 
DROP TABLE MECANICO CASCADE CONSTRAINTS; 
DROP TABLE ADMINISTRATIVO CASCADE CONSTRAINTS; 
DROP TABLE CONDUCTOR CASCADE CONSTRAINTS; 
-- Drops relaciones
DROP TABLE EJECUCION CASCADE CONSTRAINTS; 
DROP TABLE EJECUCION_CONDUCTOR CASCADE CONSTRAINTS; 
DROP TABLE SUPERVISA CASCADE CONSTRAINTS; 
--Drops vistas--
DROP VIEW VISTA_CLIENTE_PERSONA CASCADE CONSTRAINTS;
DROP VIEW VISTA_EMPLEADO_CONDUCTOR CASCADE CONSTRAINTS;
DROP VIEW VISTA_EJECUCION CASCADE CONSTRAINTS;
--Drops indices--
DROP INDEX IND_VEHICULO_EMPLEADO;
DROP INDEX IND_PARADA_RUTA;
DROP INDEX IND_ENVIO_CLIENTE;
DROP INDEX IND_EJECUCION_VEHICULO;
DROP INDEX IND_EJECUCION_RUTA;
DROP INDEX IND_EMPLEADO_DNI;
DROP INDEX IND_CLIENTE_ID;
DROP INDEX IND_EMPLEADO_NOMBRE;
DROP INDEX IND_CONDUCTOR_HORAS;
DROP INDEX IND_FECHA;
DROP INDEX IND_ESTADO;
DROP INDEX IND_EJECUCION_VEHICULO_FECHA;
DROP INDEX IND_EJECUCION_VEHICULO_RUTA;
DROP INDEX IND_PARADA_CIUDAD_RUTA;
DROP INDEX IND_SUPERVISA_SUPERVISADO;
DROP INDEX IND_EJEC_CONDUCTOR_EMPLEADO;

--CREACION TABLAS--
CREATE TABLE GPS
(
	ID_GPS	VARCHAR(9) NOT NULL,
	MODELO 	VARCHAR(10),
	NUM_SERIE	VARCHAR(10),
	PRIMARY KEY (ID_GPS)
);

CREATE TABLE EMPLEADO
(
	ID_EMPLEADO 	VARCHAR(10) NOT NULL,
	TELEFONO		NUMBER(9),
	NOMBRE_COMPLETO VARCHAR(40),
	NSS	VARCHAR(12),
	DNI	VARCHAR(9),
	PRIMARY KEY(ID_EMPLEADO)
);

CREATE TABLE CONDUCTOR
(
	ID_EMPLEADO VARCHAR(10) NOT NULL,
	LICENCIA VARCHAR(10),
	HORAS_SEMANA NUMBER(2),
	PRIMARY KEY (ID_EMPLEADO),
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
);

CREATE TABLE MECANICO
(
	ID_EMPLEADO VARCHAR(10) NOT  NULL,
	ESPECIALIDAD VARCHAR(40),
    PRIMARY KEY(ID_EMPLEADO),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
);

CREATE TABLE ADMINISTRATIVO
(
	ID_EMPLEADO VARCHAR(10),
	DEPARTAMENTO VARCHAR(12),
	PRIMARY KEY (ID_EMPLEADO),
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
);

CREATE TABLE VEHICULO (
    ID_VEHICULO   VARCHAR(5) NOT NULL,
    ID_GPS        VARCHAR(9) NOT NULL,
    ID_EMPLEADO   VARCHAR(10),
    MATRICULA     VARCHAR(7) UNIQUE,
    CAPACIDAD_KG  NUMBER(4),
    PRIMARY KEY (ID_VEHICULO),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE,
    FOREIGN KEY (ID_GPS) REFERENCES GPS(ID_GPS) ON DELETE CASCADE
);

CREATE TABLE VEHICULO_REFRIGERADO(
    ID_VEHICULO	VARCHAR(5) NOT NULL,
    TEMP_MIN 		NUMBER(2),
    TEMP_MAX		NUMBER(2),
    PRIMARY KEY (ID_VEHICULO),
    FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO (ID_VEHICULO) ON DELETE CASCADE
);

CREATE TABLE VEHICULO_ADR
(
	ID_VEHICULO VARCHAR(5) NOT NULL,
	CLASEMERCANCIA VARCHAR (10),
	PRIMARY KEY(ID_VEHICULO),
	FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULO (ID_VEHICULO) ON DELETE CASCADE
);

CREATE TABLE RUTA
(
	ID_RUTA	VARCHAR(8) NOT NULL,
	NOMBRE	VARCHAR(16),
	DISTANCIA_KM NUMBER(4),
	PRIMARY KEY (ID_RUTA)
);

CREATE TABLE PARADA
(
	N_PARADA NUMBER(2) NOT NULL,
	ID_RUTA VARCHAR(4) NOT NULL,
	CIUDAD VARCHAR(9),
	HORAPREVISTA DATE,
	PRIMARY KEY(N_PARADA, ID_RUTA),
	FOREIGN KEY(ID_RUTA) REFERENCES RUTA(ID_RUTA) ON DELETE CASCADE
);

CREATE TABLE CLIENTE
(
	ID_CLIENTE VARCHAR(5),
	NOMBRE VARCHAR(9),
	TELEFONO NUMBER(9),
	PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE PERSONA
(
	ID_CLIENTE	VARCHAR(5),
	DNI		VARCHAR(9),
	NOMBRE_COMPLETO	VARCHAR(40),
	PRIMARY KEY(DNI),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE EMPRESA
(
	ID_CLIENTE VARCHAR(5),
	NIF VARCHAR(9),
	NOMBREEMPRESA VARCHAR(9),
	PRIMARY KEY(NIF),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE ENVIO
(
    ID_ENVIO 	VARCHAR (10),
    ID_CLIENTE VARCHAR(5) NOT NULL,
    FECHA	DATE,
    ESTADO 	VARCHAR(10)  NOT NULL,
    PRIMARY KEY (ID_ENVIO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE PAQUETE
(
    N_PAQUETE 	NUMBER(4),
    ID_ENVIO 		VARCHAR (10),
    PESO 			NUMBER(5),
    CONTENIDO 		VARCHAR(30),
    PRIMARY KEY (N_PAQUETE,ID_ENVIO),	
    FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO) ON DELETE CASCADE
);

CREATE TABLE EJECUCION
(
	ID_EJECUCION VARCHAR(5),
	FECHA_EJECUCION DATE NOT NULL,
	ID_VEHICULO VARCHAR (5) NOT NULL,
	ID_RUTA VARCHAR(8) NOT NULL,
	PRIMARY KEY(ID_EJECUCION),
	FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO) ON DELETE CASCADE,
    FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA) ON DELETE CASCADE
);

CREATE TABLE EJECUCION_CONDUCTOR
(
	ID_EJECUCION VARCHAR(5),
    ID_EMPLEADO VARCHAR(10),
    PRIMARY KEY(ID_EJECUCION, ID_EMPLEADO),
    FOREIGN KEY (ID_EJECUCION) REFERENCES EJECUCION(ID_EJECUCION) ON DELETE CASCADE,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
);

CREATE TABLE SUPERVISA
(
	ID_EMPLEADO_SUPERVISADO VARCHAR(10),
	ID_EMPLEADO_SUPERVISOR VARCHAR(10),
	PRIMARY KEY(ID_EMPLEADO_SUPERVISOR, ID_EMPLEADO_SUPERVISADO),
	FOREIGN KEY (ID_EMPLEADO_SUPERVISOR) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE,
	FOREIGN KEY (ID_EMPLEADO_SUPERVISADO) REFERENCES EMPLEADO(ID_EMPLEADO) ON DELETE CASCADE
);

--CREACION DE VISTAS--
CREATE OR REPLACE VIEW VISTA_CLIENTE_PERSONA AS 
    SELECT C.ID_CLIENTE, C.NOMBRE, C.TELEFONO, P.DNI, P.NOMBRE_COMPLETO
    FROM CLIENTE C, PERSONA P
    WHERE C.ID_CLIENTE = P.ID_CLIENTE;


CREATE OR REPLACE VIEW VISTA_EMPLEADO_CONDUCTOR AS
    SELECT E.ID_EMPLEADO, E.TELEFONO, E.NOMBRE_COMPLETO, E.NSS, E.DNI, C.LICENCIA, C.HORAS_SEMANA
    FROM EMPLEADO E, CONDUCTOR C
    WHERE E.ID_EMPLEADO = C.ID_EMPLEADO;

--Son actualizables pq por ej, sobre los clientes puedo hacer actualizaciones facilmente sin q haya problemas de q la bd no sepa donde hacerlos (con empleado y conductor igual).

CREATE OR REPLACE VIEW VISTA_EJECUCION AS
    SELECT E.ID_EJECUCION, E.FECHA_EJECUCION, E.ID_VEHICULO, E.ID_RUTA, EC.ID_EMPLEADO
    FROM EJECUCION E, VEHICULO V, EMPLEADO EM, RUTA R, EJECUCION_CONDUCTOR EC
    WHERE E.ID_VEHICULO = V.ID_VEHICULO AND E.ID_RUTA = R.ID_RUTA AND E.ID_EJECUCION = EC.ID_EJECUCION AND EC.ID_EMPLEADO = EM.ID_EMPLEADO;

--No seria actualizable pq al hacer una actualizacion de cualquier tipo, la bd tendria q trabajar con 5 tablas diferentes, lo q hace que los insert (p.ej) sean complicados, ya q no sabemos donde hacerlo primero.

--CREACION INDICES--
CREATE INDEX IND_VEHICULO_EMPLEADO ON VEHICULO (ID_EMPLEADO);
CREATE INDEX IND_PARADA_RUTA ON PARADA (ID_RUTA);
CREATE INDEX IND_ENVIO_CLIENTE ON ENVIO (ID_CLIENTE);
CREATE INDEX IND_EJECUCION_VEHICULO ON EJECUCION (ID_VEHICULO);
CREATE INDEX IND_EJECUCION_RUTA ON EJECUCION (ID_RUTA);

--CREATE INDEX IND_VEHICULO_MATRICULA ON VEHICULO (MATRICULA) no hace falta pq es unique, por lo q ya tiene indice
CREATE INDEX IND_EMPLEADO_DNI ON EMPLEADO (DNI);
--CREATE INDEX IND_CLIENTE_ID ON CLIENTE (ID_CLIENTE); no pq es PK
--CREATE INDEX IND_EJECUCION_ID ON EJECUCION (ID_EJECUCION) no pq es PK

CREATE INDEX IND_EMPLEADO_NOMBRE ON EMPLEADO (NOMBRE_COMPLETO);
CREATE INDEX IND_CONDUCTOR_HORAS ON CONDUCTOR (HORAS_SEMANA);
--CREATE INDEX IND_CONDUCTOR_HORAS ON CONDUCTOR (HORAS_SEMANA) no pq muchos conductores tienen la misma licencia
CREATE INDEX IND_FECHA ON ENVIO (FECHA);
CREATE INDEX IND_ESTADO ON ENVIO (ESTADO);

CREATE INDEX IND_EJECUCION_VEHICULO_FECHA ON EJECUCION (ID_VEHICULO, FECHA_EJECUCION);
CREATE INDEX IND_EJECUCION_VEHICULO_RUTA ON EJECUCION (ID_VEHICULO, ID_RUTA);
CREATE INDEX IND_PARADA_CIUDAD_RUTA ON PARADA (ID_RUTA, CIUDAD);

CREATE INDEX IND_SUPERVISA_SUPERVISADO ON SUPERVISA (ID_EMPLEADO_SUPERVISADO);
--CREATE INDEX IND_SUPERVISA_SUPERVISOR ON SUPERVISA (ID_EMPLEADO_SUPERVISOR), haria falta????
CREATE INDEX IND_EJEC_CONDUCTOR_EMPLEADO ON EJECUCION_CONDUCTOR (ID_EMPLEADO);
