/*
Usar indice cuando:
    1. FK de tablas que se unen frecuentemente
    2. Muchos valores unicos
    3. En el where hay = o rangos, o ese valor se usa en order bys
    4. Campo unico q no se repite en varias tuplas
Si son pk no hay q crear el indice, pq ya lo hace oracle
*/

CREATE INDEX IND_VEHICULO_EMPLEADO ON VEHICULO (ID_EMPLEADO);
CREATE INDEX IND_PARADA_RUTA ON PARADA (ID_RUTA);
CREATE INDEX IND_ENVIO_CLIENTE ON ENVIO (ID_CLIENTE);
CREATE INDEX IND_EJECUCION_VEHICULO ON EJECUCION (ID_VEHICULO);
CREATE INDEX IND_EJECUCION_RUTA ON EJECUCION (ID_RUTA);

CREATE INDEX IND_VEHICULO_MATRICULA ON VEHICULO (MATRICULA);
CREATE INDEX IND_EMPLEADO_DNI ON EMPLEADO (DNI);
CREATE INDEX IND_CLIENTE_ID ON CLIENTE (ID_CLIENTE);
--CREATE INDEX IND_EJECUCION_ID ON EJECUCION (ID_EJECUCION) no pq es PK

CREATE INDEX IND_EMPLEADO_NOMBRE ON EMPLEADO (NOMBRE_COMPLETO);
CREATE INDEX IND_CONDUCTOR_HORAS ON CONDUCTOR (HORAS_SEMANA);
--CREATE INDEX IND_CONDUCTOR_HORAS ON CONDUCTOR (HORAS_SEMANA) no pq muchos conductores tienen la misma licencia
CREATE INDEX IND_FECHA ON ENVIO (FECHA);
CREATE INDEX IND_ESTADO ON ENVIO (ESTADO);

CREATE INDEX IND_EJECUCION_VEHICULO_FECHA ON EJECUCION (ID_VEHICULO, FECHA_EJECUCION);
CREATE INDEX IND_EJECUCION_VEHICULO_RUTA ON EJECUCION (ID_VEHICULO, ID_RUTA);
CREATE INDEX IND_PARADA_CIUDAD_RUTA ON PARADA (ID_RUTA, CIUDAD);

CREATE INDEX IND_SUPERVISA_SUPERVISADO ON SUPERVISA (ID_EMPLEADO_SUPERVISADO);
--CREATE INDEX IND_SUPERVISA_SUPERVISOR ON SUPERVISA (ID_EMPLEADO_SUPERVISOR), haria falta????
CREATE INDEX IND_EJECUCION_CONDUCTOR_EMPLEADO ON EJECUCION_CONDUCTOR (ID_EMPLEADO);
